travis:
  secure:
    BINSTAR_TOKEN: Zxw49YBXvUIvbUWGGQxGw1ge/Sab1oeVmIgRdm5Lr+3MTV8wxy/3M03IGiYPCUERE++EjaBKOixK19MCn8vEAcecrZtikPZxz1c32gQr2cxhlAK2SupiddD9fe0JUlcmtHfd67roAErh65G1ixd6rqirc+YrY9cXSTQzuw+Lh95eh6c8o616Sb5Im0hSc4VFxCdOhChJghtYifX2E+4KXfVXpTQ44hLs3CDt46tuJzGfezmgtd+w5G5aNmayGtgxxRBh39yLgCAv/L6arpCQs6CdbwIJWJq0pYomUWQ9MsxpCY/Ti6ZnIHOq42LPUHLtLO8HQ2GNUSPhBjGNq4s6rOX3ROaRtKMvrnZdUqYUR0oCAPvtX/F+ZmejW3ER3yfvcmRo3xs5tGBqF2ha4jGhicGmkGLWXXq2d6PnkPrW5Yimf8hOn3ZZuo3vp3MxAWpxSnqNi6OC1mZ1j9HPZGq09qDt2Uh+0q/QspLWiLUyxKt79s+ipUpJqyy8dOzLBXueUNEF5c1WtSw25wHI757whjmo5nYBBJMQUtII9tW/Zl1RpLkcQW5Vbquf9mueX1ATXlZkkNV43ljZwUJiVacKZb7YlvzeQbLFcZB6jczHuDiHXKOKJEglsFmjqADOP9pRYRNsKY/hXYca/aHL11O+y2vwTLU8X4MQfHhHl6+GOi0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
